// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCoreEnumToStringTest.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190318120245_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFCoreEnumToStringTest.MyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("DueAtDate")
                        .HasColumnName("due_at_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("my_entities");
                });
#pragma warning restore 612, 618
        }
    }
}
